/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LaurieMOOPackage;

/**
 * File: LaurieMOOJFrame.java
 * Author: Arin Santry
 * Date Started: 1/29/19
 * Date Due: 2/5/19
 * Description: GUI for LaurieMOO guessing game
 */

import javax.swing.JOptionPane;
import java.util.Arrays;

public class LaurieMOOJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LaurieMOOJFrame
     */
    public LaurieMOOJFrame() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(102, 204, 0));
    }
    
    RandomValue random = new RandomValue(); // import random value class
    String answerString; // global variable for the answer in String format
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answerLabel = new javax.swing.JLabel();
        guessLabel = new javax.swing.JLabel();
        guessTextField = new javax.swing.JTextField();
        randomButton = new javax.swing.JButton();
        mooLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        answerLabel.setText("Generate Random Number:");

        guessLabel.setText("Your Guess:");

        guessTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guessTextField.setText("????");
        guessTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessTextFieldActionPerformed(evt);
            }
        });

        randomButton.setText("Generate");
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(answerLabel)
                    .addComponent(guessLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(randomButton))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mooLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerLabel)
                    .addComponent(randomButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessLabel)
                    .addComponent(guessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mooLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
               
    /*
    * guessTextFieldActionPerformed
    * User enters their guess into text field
    * Check for correct guess
    * Count numbers of big and little moos
    * Count number of attempts
    */
    int count = 0; // guess counter initialization
    private void guessTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessTextFieldActionPerformed

        // jump between string and int to use methods
        String guessString = guessTextField.getText();
        int guessInt;
        guessInt = Integer.parseInt(guessString);
        if (random.isCorrectGuess(guessInt)) // check for right answer
        {
            String message = "LaurieMOO!!!";
            JOptionPane.showMessageDialog(null, message);
            System.exit(0); // close out of program when finished
        }
        
        // count and display numbers of big and little moos
        int numBigMoo = random.getBigMooCount(guessInt);
        int numLittleMoo = random.getLittleMooCount(guessInt);
        String bigMooString = ""; // initialize string to be displayed as empty
        String littleMooString = "";
        // setting the moo string the long way b/c for loops failed me
        if (numBigMoo == 1)
            bigMooString = "MOO!";
        if (numBigMoo == 2)
            bigMooString = "MOO! MOO!";
        if (numBigMoo == 3)
            bigMooString = "MOO! MOO! MOO!";
        if (numLittleMoo == 1)
            littleMooString = "moo.";
        if (numLittleMoo == 2)
            littleMooString = "moo. moo.";
        if (numLittleMoo == 3)
            littleMooString = "moo. moo. moo.";
        if (numLittleMoo == 4)
            littleMooString = "moo. moo. moo. moo.";
        mooLabel.setText(bigMooString + " " + littleMooString); // display big and little moos
        
        count++; // add to guess counter
        
        if (count == 10) // after 10 tries show fail message
        {
            String message = "Boo hoo - no LaurieMOO. Correct answer: " + answerString; // fail message
            JOptionPane.showMessageDialog(null, message);
            System.exit(0); // exit program when finished
        }
    }//GEN-LAST:event_guessTextFieldActionPerformed

    /*
    * randomButtonActionPerformed
    * Generate random 4-digit number when user clicks the random button
    */
    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        random.setAnswer();
        answerString = random.getAnswer();
    }//GEN-LAST:event_randomButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaurieMOOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaurieMOOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaurieMOOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaurieMOOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaurieMOOJFrame().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JTextField guessTextField;
    private javax.swing.JLabel mooLabel;
    private javax.swing.JButton randomButton;
    // End of variables declaration//GEN-END:variables
}

